== Installing the Vagrant Box

Let's go ahead and install the Vagrant box file and get everything up and running.


=== Hardware Requirements
1. 10 gigs of disk to start but may need up to 30
2. At least 8 gigs of RAM by default. Our VM will use 6 by default so we want to leave 2 gigs for the OS and others


=== Software Requirements

WARNING: You must do this *BEFORE* the class - we will not have time to do this in class.

1. Install https://www.virtualbox.org/wiki/Download_Old_Builds_5_0[VirtualBox] - I have pointed you to the past release because Vagrant doesn't work with 5.1 yet.
2. Install https://releases.hashicorp.com/vagrant/1.8.4/[Vagrant] - I have pointed you at 1.8.4 because the current version has a nasty SSH bug.

VirtualBox is a requirement. I know some of you have parallels and vmware and other virtualization tech but I only built the image for VirtualBox. My reasoning for doing this is that it is the only cross-platform FOSS VM software out there. Sorry but that's the breaks.

=== Account requirements

WARNING: You must do this *BEFORE* the class - we will not have time to do this in class.

1. https://github.com/join?source=header-home[GitHub account], if you don't have one


=== Github Repos to bring to your machine

These repos may not be finished or even available until right before the class, so we will be doing this in class.

Put these in a directory titled _os_workshop_ (not required but then it is on you to translate to your directory name in the rest of the instructions)

Clone the Crunchy DB code https://github.com/CrunchyData/crunchy-containers (optionally you can fork and then clone if you think you are going to want to make your own changes).

=== Getting the Vagrant box on your local machine

In the _os_workshop_ directory make a directory titled _vagrant_ and change into it.

---
==== Using the box on Atlas

If you are doing this at home (which I hope you did before the class) do the following commands

WARNING: You must do this *BEFORE* the class - we will not have time to do this in class.

[source, bash]
----
C:\_os_workshop\vagrant> vagrant init thesteve0/pgopen-origin
C:\_os_workshop\vagrant> vagrant up --provider=virtualbox

----

There is a *5.5 Gig* file that needs to be downloaded so it may take a while. After that is download Vagrant will bring everything up.

---

Go ahead and download the OpenShift client tools for your laptop OS. There will be a single binary in the archive - for convenience you should put it somewhere in your path. But it is also fine to place it somewhere else, you will just need to prefix you calls with the path to binary.

https://github.com/openshift/origin/releases/tag/v1.3.0-alpha.3

==== Manually copying the box off of a USB drive

If you are doing this in the class we are going to manually bring the box to your machine.

WARNING: You need to have access to your USB drive to choose this method to bring up your Vagrant box

Please try to come 15 minutes early to class so we can try to do the copying and installing before the class starts.

Copy the _Vagrantfile_ and  _*+
_ file from the USB stick into the _vagrant_ directory created above. OR just modify the _vagrant box add_ command
below to read from your USB disk directly

Then in that directory do the following commands:

[source, bash]
----

C:\_os_workshop\vagrant> vagrant box add --name pgopen-origin pgopen-openshift-origin.box
C:\_os_workshop\vagrant> vagrant init pgopen-origin
C:\_os_workshop\vagrant> vagrant up --provider=virtualbox

----

---
==== Final step

When "vagrant up" is done you should see a message that ends with:

[source]
----

==> default: Successfully started and provisioned VM with 2 cores and 4 G of memory.
==> default: To modify the number of cores and/or available memory modify your local Vagrantfile
==> default:
==> default: You can now access the OpenShift console on: https://10.2.2.2:8443/console
==> default:
==> default: Configured users are (<username>/<password>):
==> default: admin/admin
==> default: But, you can also use any username and password combination you would like to create
==> default: a new user.
==> default:
==> default: You can find links to the client libraries here: https://www.openshift.org/vm
==> default: If you have the oc client library on your host, you can also login from your host.
==> default:
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login https://10.2.2.2:8443
----

If this doesn't happen raise your hand or, if you are a good student and did this at home, email me.  If you see this then you have installed everything properly.

I know some of you are going to be curious and are going to start playing with this VM. That's OK!

Right before class (or if you break it) you just need to do the following steps:

[source, bash]
----
C:\_os_workshop\vagrant>vagrant destroy --force
C:\_os_workshop\vagrant>rm -rf .vagrant #basically delete the .vagrant dir - I do it bc I am superstitious
C:\_os_workshop\vagrant>vagrant up --provider=virtualbox
----

You don't even need to be online for this command to work! Welcome to the future.

=== Troubleshooting

. To reduce amount of memory. Edit Vagrantfile:
[source, ruby]
----
 config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
----
[start=2]
. If you have ssh authentication issues while starting the machine. Just skip ahead. You don’t need to log into the machine.
. http/ssl problems when doing login try these (in order of what to start with):
    * oc login  --insecure-skip-tls-verify=true
    * Reboot the machine
. If you have issues with builds not resolving hosts (like when building v3simplespatial):
  * Check /etc/resolv.conf in the VM (vagrant ssh and cat /etc/resolv.conf)
  * If the nameserver you have is in 10.x.x.x, change it to 8.8.8.8
  * Restart origin from within the VM (sudo systemctl restart origin)
. If must run VirtualBox 5.1 then there are instructions here on how to workaround
  * https://github.com/mitchellh/vagrant/issues/7588



<<<
