== pgadmin4

The pgadmin4 web application allows you to view a database
and execute queries in a web user interface.


=== Starting the container

[source, bash]
----

> oc new-app .\pgadmin4.json -p CCP_IMAGE_TAG=centos7-9.5-1.2.2
----

=== Accessing the App

You can access pgadmin4 by browsing the following URL:
....
http://pgadmin4-testworkshop.apps.10.2.2.2.xip.io/
....

The default admininstrative user ID is *admin@admin.org*.  The
password is *password*.

=== Creating a Server

In the left-side tree, right-click then select the
Create->Server button from the menu.

Enter a name for the database server you wish to connect to such
as *pgmaster*.  On the Connection tab, enter the service name *pgmaster* within
the Host Name/Address text field, and enter *postgres* in the User
Name field, and *password* in the Password field, then select the
Save button.

You should now see the *pgmaster* value within the tree on the left
side and a Dashboard showing various metrics collected by pgadmin4.

Expand the tree under the server name and click on the *postgres* database.
Next, click on the Tools menu item and select the Query Tool button to
expose the SQL query tool screen.  From here, you can enter
SQL commands and execute them on the server.  The button with the lighting
bolt on it will execute the SQL command.
