== Using pgadmin4 - A Web Based Admin Console

Many of you have probably used the older PGAdmin 3, which provided a desktop interface to your PostgreSQL database. We could still do that here by using _oc port-forward_ and port forwarding from the pg container in the master pod. But instead we are going to enable a  pgadmin4 web application allows to view a database and execute queries in a web user interface. Again we have a template ot make this simple and easy for you to set up through containers and templates.


=== Provisioning the container

To put the container into your application is as simple as (again in the workshop directory):

[source, bash]
----

> oc new-app .\pgadmin4.json -p CCP_IMAGE_TAG=centos7-9.5-1.2.2
----

After this run you should not see a new service with a URL for pgadmin4

mage::images/postgresql/pg_admin_overview.png[]


Go ahead and click the URL and you will be presented with the login screen

The default admininstrative user ID is *admin@admin.org*.  The
password is *password*.

=== Creating a Server

In the left-side tree, right-click then select the
Create->Server button from the menu.

Enter a name for the database server you wish to connect to such
as *pgmaster*.  On the Connection tab, enter the service name *pgmaster* within
the Host Name/Address text field, and enter *postgres* in the User
Name field, and *password* in the Password field, then select the
Save button.

You should now see the *pgmaster* value within the tree on the left
side and a Dashboard showing various metrics collected by pgadmin4.

Expand the tree under the server name and click on the *postgres* database.
Next, click on the Tools menu item and select the Query Tool button to
expose the SQL query tool screen.  From here, you can enter
SQL commands and execute them on the server.  The button with the lighting
bolt on it will execute the SQL command.

Have fun and play around for a little bit.

<<<
