== Postgresql Metrics

Sometimes when you are running your database you want to collect and visualize metrics on the instance. Now we are going to set up infrastructure to collect and visualize the data. We already added a container to the master pod called pgcollect. The pgcollect container collects 30+ metrics and sends them to the Prometheus time series data store. From there we hook up the grafana visualization tools so we can look at the metrics.

=== The Components and Installing Them

We are about to add the following pieces to our application::
 * prometheus (pod and service)
 * prometheus push gateway (pod and service)
 * grafana (pod, service, and route)

Again, there is a template to add all the pieces we need:

[source, bash]
----

> oc new-app .\metrics.json -p CCP_IMAGE_TAG=centos7-9.5-1.2.2

----

You can access grafana web application by browsing the following URL:
....
http://grafana-openshift.router.default.sv.cluster.local/login
....

The default admininstrative user ID is *admin*.  The
password is *admin*.

=== Creating a Datasource

In the upper left-side of the application, click on the dropdown
and select the Data Sources button to add a new data source.

Click on the Add Data Source button on the next screen.

Select *Prometheus* for the data source Type, enter a name of *crunchy*
for the Name field, enter http://prometheus-testworkshop.apps.10.2.2.2.xip.io/ for the URL field
and click the Add button.  You should get a green success message
if all is well at this point.

In the upper left-side of the application, click on the dropdown
and select the Dashboard->New button to add a new dashboard.

On the next screen, click on the small green tab button in the upper left
of the screen, select Add Panel->Graph to add a graph.  On the graph,
select the *crunchy* data source, then click on the Metric Lookup
field to see the available metrics being collected.  Select a metric
and it should display on the graph.

<<<
