== Installing the Vagrant Box

Let's go ahead and install the Vagrant box file and get everything up and running.


=== Hardware Requirements
1. 10 gigs of disk to start but may need up to 30
2. At least 8 gigs of RAM by default. Our VM will use 4 by default so we want to leave 4 gigs for the OS and others


=== Software Requirements

WARNING: You must do this *BEFORE* the class - we will not have time to do this in class.

1. Install https://www.virtualbox.org/wiki/Download_Old_Builds_5_0[VirtualBox]. Vagrant doesn't work with the 5.1 versions
2. Install https://releases.hashicorp.com/vagrant/1.8.4/[Vagrant]. There is a nasty SSH bug in the latest so we need to go back one

VirtualBox is a requirement. I know some of you have parallels and vmware and other virtualization tech but I only built the image for VirtualBox. My reasoning for doing this is that it is the only FOSS VM software out there. Sorry but that's the breaks.

=== Account requirements

WARNING: You must do this *BEFORE* the class - we will not have time to do this in class.

1. https://github.com/join?source=header-home[GitHub account], if you don't have one

=== Getting the Vagrant box on your local machine

You can use any directory you want but for the instructions I will make one titled  _os_workshop_.
---
==== Using the box on Atlas

If you are doing this at home (which I hope you did before the class) do the following commands


[source, bash]
----
C:\_os_workshop> vagrant init thesteve0/imagemakers
C:\_os_workshop> vagrant up --provider=virtualbox

----

There is a 2.6 Gig file that needs to be downloaded so it may take a while. After that is download Vagrant will bring everything up.

---

Go ahead and download the OpenShift client tools for your laptop OS. There will be a single binary in the archive - for convenience you should put it somewhere in your path. But it is also fine to place it somewhere else, you will just need to prefix you calls with the path to binary.

https://github.com/openshift/origin/releases/tag/v1.3.0-alpha.3

==== Manually copying the box off of a USB drive
//TODO FIX THIS

If you are doing this in the class we are going to manually bring the box to your machine.

WARNING: You need to have access to your USB drive to choose this method to bring up your Vagrant box

Please try to come 15 minutes early to class so we can try to do the copying and installing before the class starts.

Copy the _Vagrantfile_ and  _uberconf-openshift-origin.box_ file from the USB stick into the _vagrant_ directory created above.

Then in that directory do the following commands:

[source, bash]
----

C:\_os_workshop> vagrant box add --name imagemakers <sd card>\imagemakers.box
C:\_os_workshop> vagrant init imagemakers
C:\_os_workshop> vagrant up --provider=virtualbox

----

---
==== Final step

When "vagrant up" is done you should see a message that ends with:

[source]
----

==> default: Successfully started and provisioned VM with 2 cores and 4 G of memory.
==> default: To modify the number of cores and/or available memory modify your local Vagrantfile
==> default:
==> default: You can now access the OpenShift console on: https://10.2.2.2:8443/console
==> default:
==> default: Configured users are (<username>/<password>):
==> default: admin/admin
==> default: But, you can also use any username and password combination you would like to create
==> default: a new user.
==> default:
==> default: You can find links to the client libraries here: https://www.openshift.org/vm
==> default: If you have the oc client library on your host, you can also login from your host.
==> default:
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login https://10.2.2.2:8443
----

If this doesn't happen raise your hand or, if you are a good student and did this at home, email me.  If you see this then you have installed everything properly.

I know some of you are going to be curious and are going to start playing with this VM. That's OK!

Right before class (or if you break it) you just need to do the following steps:

[source, bash]
----
C:\_os_workshop\vagrant>vagrant destroy --force
C:\_os_workshop\vagrant>rm -rf .vagrant #basically delete the .vagrant dir - I do it bc I am superstitious
C:\_os_workshop\vagrant>vagrant up --provider=virtualbox
----

You don't even need to be online for this command to work! Welcome to the future.

<<<
