== Installing the Vagrant Box

Let's go ahead and install the Vagrant box file and get everything up and running. 


=== Hardware Requirements
1. 10 gigs of disk to start but may need up to 30
2. At least 8 gigs of RAM by default. Our VM will use 4 by default so we want to leave 4 gigs for the OS and others


=== Software Requirements

WARNING: You must do this *BEFORE* the class - we will not have time to do this in class.

1. Install https://www.virtualbox.org/wiki/Downloads[VirtualBox]
2. Install https://www.vagrantup.com/downloads.html[Vagrant]

=== Account requirements

WARNING: You must do this *BEFORE* the class - we will not have time to do this in class.

1. https://github.com/join?source=header-home[GitHub account], if you don't have one


=== Github Repos to bring to your machine

These repos may not be finished or even available until right before the class, so we will be doing this in class.

Put these in a directory titled _os_workshop_ (not required but then it is on you to translate to your directory name in the rest of the instructions)

*FORK* The sample code https://github.com/thesteve0/v3simple-spatial and then clone to your machine. If you just clone without the fork you will not be able to do any of the code change exercises.

Clone the Crunchy DB code https://github.com/CrunchyData/crunchy-postgres-container-94 (optionally you can fork and then clone if you think you are going to want to make your own changes).

=== Getting the Vagrant box on your local machine

In the _os_workshop_ directory make a directory titled _vagrant_ and change into it. 

---
==== Using the box on Atlas

If you are doing this at home (which I hope you did before the class) do the following commands


[source, bash]
----
C:\_os_workshop\vagrant> vagrant init thesteve0/foss4gna16
C:\_os_workshop\vagrant> vagrant up

----

There is a 3.8 Gig file that needs to be downloaded so it may take a while. After that is download Vagrant will bring everything up. 

---
==== Manually copying the box off of a USB drive

If you are doing this in the class we are going to manually bring the box to your machine.

WARNING: You need to have access to your USB drive to choose this method to bring up your Vagrant box

Please try to come 15 minutes early to class so we can try to do the copying and installing before the class starts.

Copy the _Vagrantfile_ and  _workshop.box_ file from the USB stick into the _vagrant_ directory created above.

Then in that directory do the following commands:

[source, bash]
----

C:\_os_workshop\vagrant> vagrant box add --name origin workshop.box
C:\_os_workshop\vagrant> vagrant up

----

---
==== Final step

When "vagrant up" is done you should see a message that ends with:

[source]
----

==> default: Successfully started and provisioned VM with 2 cores and 4 G of memory.
==> default: To modify the number of cores and/or available memory modify your local Vagrantfile
==> default:
==> default: You can now access the OpenShift console on: https://10.2.2.2:8443/console
==> default:
==> default: Configured users are (<username>/<password>):
==> default: admin/admin
==> default: But, you can also use any username and password combination you would like to create
==> default: a new user.
==> default:
==> default: You can find links to the client libraries here: https://www.openshift.org/vm
==> default: If you have the oc client library on your host, you can also login from your host.
==> default:
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login https://10.2.2.2:8443
----

If this doesn't happen raise your hand or, if you are a good student and did this at home, email me.  If you see this then you have installed everything properly. 

I know some of you are going to be curious and are going to start playing with this VM. That's OK! 

Right before class (or if you break it) you just need to do the following steps:

[source, bash]
----
C:\_os_workshop\vagrant>vagrant destroy --force
C:\_os_workshop\vagrant>rm -rf .vagrant #basically delete the .vagrant dir
C:\_os_workshop\vagrant>vagrant up
----

You don't even need to be online for this command to work! Welcome to the future.

<<<
