== Installing the Vagrant Box

=== Preface

We build this all-in-one from a specific Github repository.

https://github.com/openshift-evangelists/vagrant-origin

You can always build an all-in-one using the scripts and instructions in that repository. Those instructions will
allow you to build from any origin repository or branch. This is a great way to play deeply with the
source code or try out the head of the repository without waiting for us to do a build.
You can also turn on or off different features depending on what you do in the configuration files.
One example that the OpenShift Evangelists do with those scripts is to create fully loaded
VMs for workshops with all the Docker images pre-downloaded.


With that said, let's go ahead and install the Vagrant box file and get everything up and running.

=== Hardware Requirements
1. 10 gigs of disk to start but may need up to 30
2. At least 8 gigs of RAM by default. Our VM will use 4 by default so we want to leave 4 gigs for the OS and others


=== Software Requirements

WARNING: You must do this *BEFORE* the install.

1. Install https://www.virtualbox.org/wiki/Download_Old_Builds_5_0[VirtualBox]. Vagrant doesn't work with the 5.1 versions
2. Install https://releases.hashicorp.com/vagrant/1.8.4/[Vagrant 1.8.4]. There is a nasty SSH bug in the 1.8.5 and various other issues. 

You can try other combinations of this software if you want to try but we only certify Vagrant 1.8.4 and VirtualBox 5.0.latest. If all else fails go with this combination.

VirtualBox is a requirement. We know some of you have parallels and vmware and other virtualization tech but we only built the image for VirtualBox.
Our reasoning for doing this is that it is the only FOSS VM software out there. Sorry but that's the breaks.

WARNING: If you are using the new Docker for Windows, it requires HyperV which prevents VirtualBox from seeing the VT-X extension.
It is a real hassle to switch back and forth. Every time you want to go to VirtualBox you basically need to "repair it" from applications.
So turning on HyperV or VirtualBox will require at least one reboot. I found instructions on how do avoid the whole repair step
in this post by http://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx[Scott Hanselman] and while I did not try this myself I trust him.

=== Account requirements

WARNING: You must do this *BEFORE* the exercises.

1. https://github.com/join?source=header-home[GitHub account], if you don't have one

==== Using the box on Atlas

On your machine make a directory called _os_workshop_. In that directory do the following commands:

[source, bash]
----
C:\_os_workshop> vagrant init openshift/origin-all-in-one
C:\_os_workshop> vagrant up --provider=virtualbox

----

There is a 2.53 Gig file that needs to be downloaded so it may take a while. After that is download Vagrant will bring everything up.

---

Go ahead and download the OpenShift client tools for your laptop OS. There will be a single binary in the archive - for convenience you
should put it somewhere in your path. But it is also fine to place it somewhere else, you will just need to prefix you calls with the path to binary.

They will always be on the Origin latest release page

https://github.com/openshift/origin/releases

We are using 1.3.0 release of OpenShift Origin. 

---
==== Final step

When "vagrant up" is done you should see a message that ends with:

[source]
----

==> default: Successfully started and provisioned VM with 2 cores and 4 G of memory.
==> default: To modify the number of cores and/or available memory modify your local Vagrantfile
==> default:
==> default: You can now access the OpenShift console on: https://10.2.2.2:8443/console
==> default:
==> default: Configured users are (<username>/<password>):
==> default: admin/admin
==> default: But, you can also use any username and password combination you would like to create
==> default: a new user.
==> default:
==> default: You can find links to the client libraries here: https://www.openshift.org/vm
==> default: If you have the oc client library on your host, you can also login from your host.
==> default:
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login https://10.2.2.2:8443
----

If you see this then you have installed everything properly.


If you break the installation you just need to do the following steps:

[source, bash]
----
C:\_os_workshop\vagrant>vagrant destroy --force
C:\_os_workshop\vagrant>vagrant up --provider=virtualbox
----

You don't even need to be online for this command to work! Welcome to the future.

<<<
